---
abstract: 'KGS Go Server (http://www.gokgs.com/) Scraper'
author:
  - 'Ryo Anazawa (anazawa@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Path::Class: 0
  Test::Exception: 0
  Test::More: '0.98'
  Test::Pod: '1.45'
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: WWW::GoKGS
name: WWW-GoKGS
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Exporter: 0
  LWP::UserAgent: 0
  URI: 0
  Web::Scraper: 0
  parent: 0
  perl: 5.8.9
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/anazawa/p5-WWW-GoKGS
version: '0.02'
